// lib/security/report.ts
import type { ScanResult, Status } from "./types.js";

const ICON: Record<Status, string> = { pass: "✅", fail: "❌", advisory: "🔍", error: "⚠️", info: "ℹ️" };

export function renderReport(r: ScanResult): string {
  const rows = r.findings
    .map((f) => `| ${ICON[f.status]} | ${f.severity.toUpperCase()} | **${f.title}** | ${f.category} | ${f.detail} |`)
    .join("\n");
  return `# MCPHub Security Scan

**Target:** \`${r.target}\`
**Scanned:** ${r.scannedAt}
**Score:** ${r.score}/100 — Grade ${r.grade}
**Tools inspected:** ${r.tools.length}

| | Severity | Finding | Category | Detail |
|---|---|---|---|---|
${rows}

_Generated by MCPHub Security Scan. Advisory items require manual review; they cannot be verified externally._
`;
}

export interface LeaderboardRow {
  target: string;
  grade: string;
  score: number;
}

const GRADE_RANK: Record<string, number> = { F: 0, D: 1, C: 2, B: 3, A: 4 };

export function renderLeaderboard(rows: LeaderboardRow[]): string {
  const sorted = [...rows].sort(
    (a, b) => (GRADE_RANK[a.grade] ?? 9) - (GRADE_RANK[b.grade] ?? 9) || a.score - b.score || a.target.localeCompare(b.target)
  );
  const body = sorted.map((r) => `| ${r.target} | ${r.grade} | ${r.score} |`).join("\n");
  return `# State of MCP Security — Leaderboard

_Worst grade first. Generated by MCPHub Security Scan (passive, read-only)._

| Server | Grade | Score |
|---|---|---|
${body}
`;
}
